name:                TheSpellChecker
version:             0.1.0.0
github:              "SteinarSi/TheSpellChecker"
license:             BSD3
author:              "Steinar"
maintainer:          "Steinar.Simonnes@gmail.com"
copyright:           "2022 Steinar"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/SteinarSi/TheSpellChecker#readme>

dependencies:
- base >= 4.7 && < 5
- cyclotomic
- megaparsec
- text
- transformers
- mtl
- text-show
- HUnit
- numbers
- vector-sized
- ghc-typelits-knownnat
- ghc-typelits-extra
- split
- finite-typelits
- leancheck
- Decimal
- approximate-equality
- type-level-numbers
- gloss <= 1.13.2.1

library:
  source-dirs: src

executables:
  TheSpellChecker-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TheSpellChecker

tests:
  TheSpellChecker-test:
    main:                TestMain.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TheSpellChecker
